window.___jsl=window.___jsl||{};
window.___jsl.h=window.___jsl.h||'m;\/_\/apps-static\/_\/js\/widget\/__features__\/rt=j\/ver=z_zkNmeRCAw.pt_BR.\/sv=1\/am=!TxaHJQ_ELSaIORy5WA\/d=1\/';
window.___jsl.l=[];
window.___gpq=[];
window.gapi=window.gapi||{};
window.gapi.plusone=window.gapi.plusone||(function(){
  function f(n){return function(){window.___gpq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
function __bsld(){var p=window.gapi.plusone=window.googleapisv0.plusone;var f;while(f=window.___gpq.shift()){
  p[f]&&p[f].apply(p,window.___gpq.shift())}
p=window.gapi.plus=window.googleapisv0.plus;while(f=window.___gbq.shift()){
  p[f]&&p[f].apply(p,window.___gbq.shift())}
if (gadgets.config.get("gwidget")["parsetags"]!=="explicit"){gapi.plusone.go();}}
window.___gbq=[];
window.gapi.plus=window.gapi.plus||(function(){
  function f(n){return function(){window.___gbq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
window.__GOOGLEAPIS=window.__GOOGLEAPIS||{};
window.__GOOGLEAPIS.iframes=window.__GOOGLEAPIS.iframes||{};
window.__GOOGLEAPIS.iframes.plus=window.__GOOGLEAPIS.iframes.plus||{url:':socialhost:/u/:session_index:/_/pages/badge'};window['___jsl'] = window['___jsl'] || {};window['___jsl']['uc'] = 'https:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['u'] = 'https:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['f'] = ['googleapis.client','plusone','gcm_ppb'];window['___jsl']['ms'] = 'https://plus.google.com';(window['___jsl']['ci'] = (window['___jsl']['ci'] || [])).push({"gwidget":{"parsetags":"onload"},"iframes":{"sharebox":{"params":{"json":"&"},"url":":socialhost:/:session_prefix:_/sharebox/dialog"},"plus":{"url":":socialhost:/:session_prefix:_/pages/badge"},":socialhost:":"https://plusone.google.com","plusone_m":{"url":":socialhost:/:session_prefix:_/+1/fastbutton","params":{"count":"","size":"","url":""}},"card":{"params":{"style":"#","userid":"&"},"url":":socialhost:/u/:session_index:/_/hovercard/card"},"plusone":{"url":":socialhost:/:session_prefix:_/+1/fastbutton","params":{"count":"","size":"","url":""}}},"googleapis.config":{"requestCache":{"enabled":true},"methods":{"chili.people.list":true,"pos.plusones.list":true,"pos.plusones.get":true,"chili.people.get":true,"pos.plusones.insert":true,"chili.activities.list":true,"pos.plusones.delete":true,"chili.activities.get":true,"chili.activities.search":true,"pos.plusones.getSignupState":true},"versions":{"chili":"v1","pos":"v1"},"rpc":"/rpc","transport":{"isProxyShared":true},"sessionCache":{"enabled":true},"root-1p":"https://clients6.google.com","root":"https://www.googleapis.com","xd3":"/static/proxy.html","developerKey":"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ","auth":{"useInterimAuth":false}}});var gapi=window.gapi||{};gapi.client=window.gapi&&window.gapi.client||{};
(function(){var w=void 0,x=void 0,y="___jsl",S="h",z="l",T="m",A="ms",o="cu",U="c",V="cm",W="o",q="p",j="q",B="lc",C="Q",r="I",s="_",t="https://ssl.gstatic.com",X="/webclient/js",Y="/webclient/jsx/",D="https://apis.google.com",E=".js",Z="gcjs-3p",$=/^(https?:)?\/\/([^/:@]*)(:[0-9]+)?(\/[\w.,:!=/-]*)(\?[^#]*)?(#.*)?$/,F=/^[?#]([^&]*&)*jsh=([^&]*)/,G="d",l="r",aa="f",p="m",H="n",ba="sync",ca="callback",u="config",I="nodep",J="gapi.load: ",K=function(a,b){w&&w(a,b);throw J+a+(b&&" "+b);},L=function(a){x&&
x(a);var b=window.console;b&&b.warn(J+a)},da=function(a,b,c){a=a[S];if(b=b&&F.exec(b)||c&&F.exec(c))try{a=decodeURIComponent(b[2])}catch(d){L("Invalid hint "+b[2])}return a},M=function(a){a.sort();for(var b=0;b<a.length;)!a[b]||b&&a[b]==a[b-1]?a.splice(b,1):++b},N=function(a,b){for(var c=!0,d=0,f=0,e,g;c&&(e=a[d])&&(g=b[f]);)e==g?++d:e<g&&(c=!1),++f;return c&&!e},ea=function(a){if("loading"!=document.readyState)return!1;if("undefined"!=typeof window.___gapisync)return window.___gapisync;if(a&&(a=
a[ba],"undefined"!=typeof a))return a;for(var a=document.getElementsByTagName("meta"),b=0,c;c=a[b];++b)if("generator"==c.getAttribute("name")&&"blogger"==c.getAttribute("content"))return!0;return!1},O=function(a,b){if(ea(a))document.write('<script src="'+encodeURI(b)+'"><\/script>');else{var c=b,d=document.createElement("script");d.setAttribute("src",c);d.async=!0;c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(d,c)}},P=function(a,b,c,d,f,e){var g=c.shift(),h;h=g==l?t:g==p?
d[A]||D:(h=c.shift())&&h.replace(/\/+$/,"");var k;g==l?(k=c.shift(),k=(k.indexOf(Y)?X+"/":"")+k):k=c.shift();var i=g==G,m=i&&c.shift()||Z,c=i&&c.shift();if(g==G)e=b,b=k,f=m,a="/"+a.join(":")+(e.length?"!"+e.join(":"):"")+E+"?container="+f+"&c=2&jsload=0",b&&(a+="&r="+b),"d"==c&&(a+="&debug=1");else if(g==l||g==aa)e=b,b=k,a=(b.indexOf("/")?"/":"")+b+"/"+a.join("__")+(e.length?"--"+e.join("__"):"")+E;else if(g==p||g==H)b=k,a=a.join(",").replace(/\./g,"_").replace(/-/g,"_"),a=b.replace("__features__",
a),a=f[I]?a.replace("/d=1/","/d=0/"):a,e&&(a.match(/\/$/)||(a+="/"),a+="cb=gapi."+encodeURIComponent(e));else return L("Unknown hint type "+g),"";if(!h)return"";h+=a;a=h;e=d;if(b=d=$.exec(a))if(b=!/\.\.|\/\//.test(d[4]))b:if(b=a,d=d[2],g==l)b=b.substr(0,t.length)==t;else if(g==p)d=e[A]||D,b=b.substr(0,d.length)==d;else{g=e[T];if(d&&g){g=g.split(",");e=0;for(b=g.length;e<b;++e)if(f=g[e],c=d.lastIndexOf(f),(0==c||"."==f.charAt(0)||"."==d.charAt(c-1))&&d.length-f.length==c){b=!0;break b}}b=!1}b||K("Invalid URI",
a);return h},fa=function(a,b,c){(a[j]=a[j]||[]).push([b,c])},R=function(a){a[j]&&0<a[j].length&&(window.gapi.load||Q).apply(null,a[j].shift())},v=function(a){if(a)try{a()}catch(b){return b}return null},ga=function(){if(gapi[s])return gapi[s];var a;if((a=Object.create)&&/\[native code\]/.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return gapi[s]=a},ha=function(a,b,c,d,f){var e=f[C]=f[C]||[],g=f[B]=f[B]||{};e.push([a,b,d]);gapi[c]=function(b){gapi[c]=void 0;if(!g[a]){g[a]=b;for(var b=e,d=
g,i=f,m;b[0]&&d[b[0][0]];){var n=b.shift(),j=n[2],l=i;j&&(gapi.config?gapi.config.update(j):(l[o]=l[o]||[]).push(j));d[n[0]].call(window,ga());d[n[0]]=!0;(n=v(n[1]))&&!m&&(m=n)}if(m)throw m;}}},ia=function(a){a[r]||(a[r]=0);return"loaded"+a[r]++},Q=function(a,b){var c,d={};"function"!==typeof b?(d=b||{},c=d[ca]):c=b;var f=window[y]=window[y]||{},e=da(f,window.location.search,window.location.hash),g=e&&!!e.match(/\/gapi\/|ms=gapi/);if(!g&&f[q])fa(f,a,b);else{e||K("No hint present","");var h=e.split(";"),
k=h[0]==p||h[0]==H,e=a.split(":");d[I]||M(e);var i=f[z]=f[z]||[];M(i);if(g){if(!N(e,i)&&(g=ia(f),h=P(e,i,h,f,d,g))){ha(h,c,g,d[u],f);i.push.apply(i,e);O(d,h);return}c&&c()}else{if(!N(e,i)){var j=k?V:U,h=P(e,i,h,f,d,null);d[u]&&(f[o]=f[o]||[]).push(d[u]);if(h){f[q]=e;f[W]=1;f[j]=function(){delete f[q];delete f[j];var a=v(c);R(f);if(a)throw a;};i.push.apply(i,e);O(d,h);return}}d=v(c);R(f);if(d)throw d;}}};gapi.loader={load:Q}})();
gapi.load=window.___jsl&&window.___jsl.il&&window.gapi&&window.gapi.load||gapi.loader.load;
(window.gapi=window.gapi||{}).load=window.___jsl&&window.___jsl.il&&window.gapi.load||gapi.load;
gapi.load('googleapis.client:plusone:gcm_ppb', {'callback': window['__bsld']  });